export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const CHALLENGE_REPOSITORY = Symbol('CHALLENGE_REPOSITORY');
export const TESTCASE_REPOSITORY = Symbol('TESTCASE_REPOSITORY');